blank_issues_enabled: false
contact_links:
  - name: Nexus SUPRA™ — General discussion
    url: https://github.com/gkfsupra/sha713-factory/discussions
    about: Use discussions for ideas and strategy.
