name: Codex PDF + QR Generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install reportlab
          pip install qrcode[pil]

      - name: Generate bilingual PDF with SHA-713 hash
        run: |
          python scripts/generate_pdf.py --lang en,es --sign sha256

      - name: Generate QR Code
        run: |
          python scripts/generate_qr.py --input output/codex.pdf --output output/codex_qr.png

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: codex-output
          path: output/

