name: POSE-713 Verify
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Verify MANIFEST-713 hashes
        run: |
          jq -r '.files[] | "\(.path) \(.sha256)"' MANIFEST-713.json > expected.txt
          while read -r path expected; do
            [ -f "$path" ] || (echo "Missing $path" && exit 1)
            calc=$(sha256sum "$path" | awk '{print $1}')
            [ "$calc" = "$expected" ] || (echo "Hash mismatch $path" && echo "expected $expected / got $calc" && exit 1)
          done < expected.txt
          echo "POSE-713 verified ✅"
